FROM node:20.12.0-alpine3.19
WORKDIR /usr/src/app
COPY package.json package-lock.json turbo.json tsconfig.json ./
COPY apps ./apps

COPY packages ./packages

ENV DATABASE_URL=postgres://postgres:password@localhost:5432/fintrix
# Install dependencies
RUN npm install

RUN npm run db:generate

CMD ["npm", "run", "start-user-app"]
